### ISSUE TITLE
Publish X-ray and CT of positive people?

### ISSUE THREAD

**Issue by FezVrasta** [pcm-dpc/COVID-19#105]
**Type of issue**: richiesta di dati

## Summary

Would it be possible to provide x-rays and CT scans of positive patients? It would be useful to develop machine learning models to identify more cases.

**Comment by brucellino** [comment]
Can you please point to other cases where this approach has been useful, in order to support this hypothesis? The current protocol specified by the WHO indicates [real time PCR](https://www.who.int/emergencies/diseases/novel-coronavirus-2019/technical-guidance/laboratory-guidance) from patient swabs as the means of diagnosis.

I am not a public health practitioner, but I can't find anywhere in the literature so far suggestion that diagnosis via imagery would be effective at scale. Collecting and anonymising data presents its own challenges, not to mention training the data set.

If indeed this data were collected, it would likely be deposited in a [bio bank](https://www.bbmri-eric.eu/) rather than a github repo.

**Comment by FezVrasta** [comment]
The readme in this repository gives a good explanation https://github.com/ieee8023/covid-chestxray-dataset

**Comment by umbros** [comment]
@FezVrasta thank you for your suggestion. At present we do not receive these data and I think we will not receive them.
