### ISSUE TITLE
Not unique region denomination and region code

### ISSUE THREAD

**Issue by mydozer** [pcm-dpc/COVID-19#123]
Could you please reopen the issue #92 and fix region denomination or region code so they are unique?

Thank you!

**Comment by AnthonyEbert** [comment]
È estremamente importante che `denominazione_regione` non cambi. Non è sufficiente usare `codice_regione` perché questa informazione è inutile da sola e non può essere utilizzata con dati internazionali. 

It is extremely important that `denominazione_regione` does not change. It is not enough to use `codice_regione` because this information is useless by itself and can't be used with international data.

**Comment by mydozer** [comment]
> It is extremely important that `denominazione_regione` does not change. It is not enough to use `codice_regione` because this information is useless by itself and can't be used with international data.

The denominazione_regione has alredy changed once and now has a usless trailing space in it. It is a good idea to avoid models based on raw datasets. I admit is boring adapt the data normalization flow day by day, but it is the way to have a clean input.

**Comment by umbros** [comment]
@AnthonyEbert, we are improving the data provided, including the denominations, any changes are notified in CHANGELOG, as was done yesterday for the Autonomous Province of Bolzano and Trento
