### ISSUE TITLE
Data type and consolidation

### ISSUE THREAD

**Issue by piedea** [pcm-dpc/COVID-19#335]
All the data pubished should be consolidated in a database manner in order to allow everibody to work on them and be helpful for the entire scientific world community.

Please, at least, give us data in CSV downloadable files and english language (format numbers) and ask to every contributor to give the data in the same format.

Thank you

**Comment by FedericoStra** [comment]
What do you consider to be "database manner"? It's provided both in CVS and JSON form. That should be sufficient, right?

> Please, at least, give us data in CSV downloadable files

The files are downloadable. You just have to press the "Raw" button and you get this: https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

Otherwise you can clone the entire repository with `git clone https://github.com/pcm-dpc/COVID-19.git` and you'll get all the files.

**Comment by umbros** [comment]
Thank you @FedericoStra :).
Piedea do you need a particular type of file?

**Comment by piedea** [comment]
In order to follow with prediction analysts, it’s necessary to have all the data available, on a national basis, consolidated in one large excel table csv format and international numeric format. 
Most likely will be an important work of modeling and table population. 
I’m imaging a large and strait forward simple table containing all the data published in Italy since the raising of the infection. 
I looking forward to ear from you. 
Thank you 

Pietro De Angelis
pierodeangelis@gmail.com

**Comment by piedea** [comment]
> What do you consider to be "database manner"? It's provided both in CVS and JSON form. That should be sufficient, right?
> 
> > Please, at least, give us data in CSV downloadable files
> 
> The files are downloadable. You just have to press the "Raw" button and you get this: https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
> 
> Otherwise you can clone the entire repository with `git clone https://github.com/pcm-dpc/COVID-19.git` and you'll get all the files.

Thanks but those are data for one day only. Its necessary to have all the data in one file mybe database or large excel folder. Otherwise, day by day, it's a problem to agrregate them all.
It's very importat do to this job of consolidation otherwise all of the scientist they have to do singularly this task.
Thank you

**Comment by vcaponi** [comment]
Whoever works with the data appreciates that those are actually given baily with a new one-day data file, so that a small amount of data can be automatically downloaded to extend the dataset one has created already. The alternative of updating one big dataset every day implies that each day we would need to re-download all the previous downloaded data together with the update. What's "scientific" in it? BTW, that's the French strategy...

**Comment by BlueHatbRit** [comment]
Personally I think this data is in a great format, it's really well formatted and can be used for a wide range of tasks. You will never be able to please everyone with the data format, at least this way it can be easily pulled into any shape you need and redundant data can behind. No matter what format is provided, it will be imperfect for some people.

If you want to consolidate the data for your own purposes you could do as I've done here - https://github.com/BlueHatbRit/covid-19-data i've setup a repo with a github action to run every hour which then transforms the data into a format useful to me. In this case it translates the national data into JSON with English keys (sadly I don't speak Italian).

**Comment by FedericoStra** [comment]
> > The files are downloadable. You just have to press the "Raw" button and you get this: https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv
> Thanks but those are data for one day only. Its necessary to have all the data in one file mybe database or large excel folder. Otherwise, day by day, it's a problem to agrregate them all.

I'm sorry to contradict you, but the file I linked is a single file containing the data for all the days. Have you opened it? Similarly, for the JSON data https://github.com/pcm-dpc/COVID-19/tree/master/dati-json.

**Comment by GiacomoA92** [comment]
Maybe you missed it. The repository contains files for data for a specific day **and** files with the data for all days together.
The link @FedericoStra posted in fact contains all data for Italy since the end of February.
If you are unable to discern this maybe you should avoid doing any research which certainly requires more attention that opening an URL and setting that there are in fact multiple days listed.

If you are asking something else then I believe you must specify what do you mean.

**Comment by s6carlo** [comment]
The format is great, you can easily use them wherever you want.

Downloading csv is very simple, just using a link like this:
[https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv](https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv)

You can import csv into Excel (data from web) or in Google Sheet in one command:
`=importdata("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv")`

Here an example of import and use in Google Sheet 
[https://docs.google.com/spreadsheets/d/1iPT1yRCXNXxweHidcef_6qcK9fOH-gMPDubS0VEMt40/edit?usp=sharing
](https://docs.google.com/spreadsheets/d/1iPT1yRCXNXxweHidcef_6qcK9fOH-gMPDubS0VEMt40/edit?usp=sharing
)
and Google Datastudio
[https://datastudio.google.com/open/1rooFg1w9M29Su_Y2uc6-Y1o_RHGcqMB0](https://datastudio.google.com/open/1rooFg1w9M29Su_Y2uc6-Y1o_RHGcqMB0)

**Comment by umbros** [comment]
Thank you to all for the support given to @piedea
